export const ADD_TO_CART = "ADD_TO_CART"
export const UPDATE_CART_QUANTITY = "UPDATE_CART_QUANTITY";
export const DELETE_FROM_CART = "DELETE_FROM_CART"
export const ADD_MULTIPLE_TO_CART = "ADD_MULTIPLE_TO_CART";
export const ADD_COMMENTS = "ADD_COMMENTS";
export const CLEAR_CART = "CLEAR_CART";
